"""
Step 5: YAML 파일 생성

YOLO 훈련을 위한 데이터셋 설정 파일(ppe_dataset.yaml)을 생성합니다.

## YAML 파일이란?
데이터셋의 구조와 클래스 정보를 정의하는 설정 파일입니다.
YOLO 모델이 훈련할 때 이 파일을 읽어서 다음 정보를 파악합니다:
- 이미지가 어디에 있는지 (train/val/test 경로)
- 몇 개의 클래스를 탐지할지 (nc: number of classes)
- 각 클래스의 이름이 무엇인지 (names: helmet, vest 등)

## 언제 사용되나요?
1. 모델 훈련 시:
   ```python
   from ultralytics import YOLO
   model = YOLO('yolov8n.pt')
   model.train(data='configs/ppe_dataset.yaml', epochs=100)
   ```

2. 모델 검증 시:
   ```python
   model.val(data='configs/ppe_dataset.yaml')
   ```

3. 모델 추론 시 (클래스 이름 참조):
   ```python
   results = model.predict(source='image.jpg')
   ```

## 왜 상대 경로를 사용하나요?
- 절대 경로: /Users/joonho/workspace/.../images
  → 다른 개발자 PC에서는 경로가 다르므로 작동 안 함
- 상대 경로: ../images (configs 폴더 기준)
  → 프로젝트만 복사하면 어디서든 작동

## YAML 파일 구조
```yaml
path: ../images          # 데이터셋 루트 경로 (configs 기준 상대 경로)
train: train/images      # 훈련 이미지 경로 (path 기준)
val: val/images          # 검증 이미지 경로 (path 기준)
test: test/images        # 테스트 이미지 경로 (path 기준)
nc: 2                    # 클래스 수 (number of classes)
names:
  0: helmet              # 클래스 ID: 이름 매핑
  1: vest
```

## 입력/출력
- 입력: 없음 (하드코딩된 설정)
- 출력: configs/ppe_dataset.yaml
"""

from pathlib import Path


def generate_yaml():
    """
    데이터셋 YAML 파일 생성

    처리 과정:
    1. 경로 설정
    2. configs 디렉토리 생성
    3. YAML 내용 작성 (상대 경로 사용)
    4. 파일 저장
    5. 결과 출력

    Returns:
        Path: 생성된 YAML 파일 경로
    """

    # =========================================================================
    # 1. 경로 설정
    # =========================================================================
    # 프로젝트 루트 디렉토리
    base_dir = Path(__file__).parent.parent.parent
    # 설정 파일을 저장할 디렉토리
    config_dir = base_dir / 'configs'

    # =========================================================================
    # 2. 설정 디렉토리 생성
    # =========================================================================
    config_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("Step 5: YAML 파일 생성")
    print("=" * 50)

    # =========================================================================
    # 3. YAML 내용 작성
    # =========================================================================
    # 상대 경로 사용 - configs 폴더 기준
    # ../images는 configs의 상위 폴더에 있는 images 폴더를 의미
    yaml_content = """# PPE Detection Dataset Configuration
# Generated by step5_generate_yaml.py

# 데이터셋 경로 (configs 폴더 기준 상대 경로)
# YOLO는 이 path를 기준으로 train/val/test 경로를 찾음
path: ../images

# 데이터 분할
# path 아래의 하위 경로를 지정
train: train/images      # path/train/images → images/train/images
val: val/images          # path/val/images → images/val/images
test: test/images        # path/test/images → images/test/images

# 클래스 수 (number of classes)
nc: 2

# 클래스 이름
# YOLO는 라벨 파일의 class_id (0, 1, ...)를 이 이름으로 매핑
names:
  0: helmet              # class_id 0 → "helmet"
  1: vest                # class_id 1 → "vest"
"""

    # =========================================================================
    # 4. 파일 저장
    # =========================================================================
    yaml_path = config_dir / 'ppe_dataset.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    # =========================================================================
    # 5. 결과 출력
    # =========================================================================
    print(f"✅ YAML 파일 생성 완료!")
    print(f"   - 경로: {yaml_path}")
    print()
    print("📄 파일 내용:")
    print("-" * 40)
    print(yaml_content)
    print()

    return yaml_path


if __name__ == '__main__':
    # 스크립트 직접 실행 시 YAML 생성
    generate_yaml()
