"""
Step 4: YAML 파일 생성

YOLO 훈련을 위한 데이터셋 설정 파일을 생성합니다.
"""

import os
from pathlib import Path


def generate_yaml():
    """데이터셋 YAML 파일 생성"""

    # 경로 설정
    base_dir = Path(__file__).parent.parent.parent
    config_dir = base_dir / 'configs'
    images_dir = base_dir / 'images'

    # 설정 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("Step 4: YAML 파일 생성")
    print("=" * 50)

    # YAML 내용
    yaml_content = f"""# PPE Detection Dataset Configuration
# Generated by step4_generate_yaml.py

# 데이터셋 경로 (절대 경로)
path: {images_dir}

# 데이터 분할
train: train/images
val: val/images
test: test/images

# 클래스 수
nc: 2

# 클래스 이름
names:
  0: helmet
  1: vest
"""

    # 파일 저장
    yaml_path = config_dir / 'ppe_dataset.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"✅ YAML 파일 생성 완료!")
    print(f"   - 경로: {yaml_path}")
    print()
    print("📄 파일 내용:")
    print("-" * 40)
    print(yaml_content)
    print()

    return yaml_path


if __name__ == '__main__':
    generate_yaml()
