"""
Step 5: YAML 파일 생성

YOLO 훈련을 위한 데이터셋 설정 파일(ppe_dataset.yaml)을 생성합니다.

## YAML 파일이란?
데이터셋의 구조와 클래스 정보를 정의하는 설정 파일입니다.
YOLO 모델이 훈련할 때 이 파일을 읽어서 다음 정보를 파악합니다:
- 이미지가 어디에 있는지 (train/val/test 경로)
- 몇 개의 클래스를 탐지할지 (nc: number of classes)
- 각 클래스의 이름이 무엇인지 (names: helmet, vest 등)

## 언제 사용되나요?
1. 모델 훈련 시:
   model.train(data='configs/ppe_dataset.yaml', ...)

2. 모델 검증 시:
   model.val(data='configs/ppe_dataset.yaml')

## 생성되는 파일 예시
```yaml
path: /path/to/images        # 데이터셋 루트 경로
train: train/images          # 훈련 이미지 경로
val: val/images              # 검증 이미지 경로
test: test/images            # 테스트 이미지 경로
nc: 2                        # 클래스 수
names:
  0: helmet                  # 클래스 ID와 이름 매핑
  1: vest
```
"""

from pathlib import Path


def generate_yaml():
    """데이터셋 YAML 파일 생성"""

    # 경로 설정
    base_dir = Path(__file__).parent.parent.parent
    config_dir = base_dir / 'configs'

    # 설정 디렉토리 생성
    config_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("Step 5: YAML 파일 생성")
    print("=" * 50)

    # YAML 내용 (상대 경로 사용 - configs 폴더 기준)
    yaml_content = """# PPE Detection Dataset Configuration
# Generated by step5_generate_yaml.py

# 데이터셋 경로 (configs 폴더 기준 상대 경로)
path: ../images

# 데이터 분할
train: train/images
val: val/images
test: test/images

# 클래스 수
nc: 2

# 클래스 이름
names:
  0: helmet
  1: vest
"""

    # 파일 저장
    yaml_path = config_dir / 'ppe_dataset.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"✅ YAML 파일 생성 완료!")
    print(f"   - 경로: {yaml_path}")
    print()
    print("📄 파일 내용:")
    print("-" * 40)
    print(yaml_content)
    print()

    return yaml_path


if __name__ == '__main__':
    generate_yaml()
